# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recovercheck < Formula
  desc "A tool to check for panic recovery in Go code"
  homepage "https://github.com/cksidharthan/recovercheck"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v0.0.2/recovercheck_Darwin_x86_64.tar.gz"
      sha256 "859f63126feac45e857d7e6249678da55edd94249d76829c94903587a751e2b8"

      def install
        bin.install "recovercheck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v0.0.2/recovercheck_Darwin_arm64.tar.gz"
      sha256 "f653e4bed87d5bcb6594d90c0f784a53008f3aa8f361b4528d82ce64443930ab"

      def install
        bin.install "recovercheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v0.0.2/recovercheck_Linux_x86_64.tar.gz"
      sha256 "621fcf0e5ad824d00bbc07cf924845bf6c1167af83edc24a28fd731b5a58d291"
      def install
        bin.install "recovercheck"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v0.0.2/recovercheck_Linux_arm64.tar.gz"
      sha256 "76162cb84b193c6643059217b416d3d6d1f217af53be835268b656165f5e8c16"
      def install
        bin.install "recovercheck"
      end
    end
  end

  def caveats
    <<~EOS
      recovercheck is a tool to check for panic recovery in Go code.
      Run 'recovercheck' to start the tool.
    EOS
  end

  test do
    system "#{bin}/recovercheck", "--version"
  end
end
