# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recovercheck < Formula
  desc "A tool to check for panic recovery in Go code"
  homepage "https://github.com/cksidharthan/recovercheck"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.2.0/recovercheck_Darwin_x86_64.tar.gz"
      sha256 "d3be2c36bed86a3c1581963f548feb927b37a62ad945f24ec495771cbaa309ca"

      def install
        bin.install "recovercheck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.2.0/recovercheck_Darwin_arm64.tar.gz"
      sha256 "5eba030053a5ebf6eed181e048089e2ab236cadb0c986be6a8064856228c261c"

      def install
        bin.install "recovercheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.2.0/recovercheck_Linux_x86_64.tar.gz"
      sha256 "b8c04310b83adac6e5b97e3688aeec1f032e8559f2bbca580f63a804cf6a9ee5"
      def install
        bin.install "recovercheck"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.2.0/recovercheck_Linux_arm64.tar.gz"
      sha256 "9949f20b87e03fa37c7045a7f56847f6d0f412ac427a80d1c95f9dbbec1c9a30"
      def install
        bin.install "recovercheck"
      end
    end
  end

  def caveats
    <<~EOS
      recovercheck is a tool to check for panic recovery in Go code.
      Run 'recovercheck' to start the tool.
    EOS
  end

  test do
    system "#{bin}/recovercheck", "--version"
  end
end
