# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Browser < Formula
  desc "A user-friendly browser for S3-compatible object storage"
  homepage "https://github.com/cksidharthan/s3-browser"
  version "1.0.0"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/cksidharthan/s3-browser/releases/download/v1.0.0/s3-browser_Darwin_x86_64.tar.gz"
      sha256 "c41b359fa7f07fca13fb901bed4f891e7e224310e989c6cc4e26e592d7b358b9"

      def install
        bin.install "s3-browser"
      end
    end
    on_arm do
      url "https://github.com/cksidharthan/s3-browser/releases/download/v1.0.0/s3-browser_Darwin_arm64.tar.gz"
      sha256 "3398bd129c1f6f4c842fef9b9681a969d91b3f408a87694d2f61e9e9833d006d"

      def install
        bin.install "s3-browser"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cksidharthan/s3-browser/releases/download/v1.0.0/s3-browser_Linux_x86_64.tar.gz"
        sha256 "1fea6c0a1024b327031ac6e4cdd089e0969904cf40e0d3e965b9086383a10bce"

        def install
          bin.install "s3-browser"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cksidharthan/s3-browser/releases/download/v1.0.0/s3-browser_Linux_arm64.tar.gz"
        sha256 "1580c5aac956b82dcbef54a5e5643040bc0c54ccaebbf856fb5b5069ff0eb1c7"

        def install
          bin.install "s3-browser"
        end
      end
    end
  end

  def caveats
    <<~EOS
      s3-browser is a browser for S3-compatible storage.
      Run 's3-browser' to start the application.
    EOS
  end

  test do
    system "#{bin}/s3-browser", "--version"
  end
end
