# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3Browser < Formula
  desc "A user-friendly browser for S3-compatible object storage"
  homepage "https://github.com/cksidharthan/s3-browser"
  version "1.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cksidharthan/s3-browser/releases/download/v1.1.0/s3-browser_Darwin_x86_64.tar.gz"
      sha256 "0b8543b082158dbc15888d983e1ebd38a4aba2f5a5af4463f39e467282924a8d"

      def install
        bin.install "s3-browser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cksidharthan/s3-browser/releases/download/v1.1.0/s3-browser_Darwin_arm64.tar.gz"
      sha256 "4a4dde8fc3b2843bb2530bbfb205c184bad49ca6391e617e8d233aad4a26d0a4"

      def install
        bin.install "s3-browser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cksidharthan/s3-browser/releases/download/v1.1.0/s3-browser_Linux_x86_64.tar.gz"
      sha256 "eefdd8361b78cfe2a6633bd2b98e1920450acbba337c8b5928241535bc13199c"
      def install
        bin.install "s3-browser"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cksidharthan/s3-browser/releases/download/v1.1.0/s3-browser_Linux_arm64.tar.gz"
      sha256 "3c8637bbae55f6a2f7bc868c6598d1826535ee4d1da597dc40cad64dffe12712"
      def install
        bin.install "s3-browser"
      end
    end
  end

  def caveats
    <<~EOS
      s3-browser is a browser for S3-compatible storage.
      Run 's3-browser' to start the application.
    EOS
  end

  test do
    system "#{bin}/s3-browser", "--version"
  end
end
