# This file was generated by GoReleaser. DO NOT EDIT.
cask "recovercheck" do
  name "recovercheck"
  desc "A tool to check for panic recovery in Go code"
  homepage "https://github.com/cksidharthan/recovercheck"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recovercheck"

  on_macos do
    on_intel do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Darwin_x86_64.tar.gz"
      sha256 "ab532e10ab225f8be198da271704a95bfc18da9154a5dc59e0480bdff425ce78"
    end
    on_arm do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Darwin_arm64.tar.gz"
      sha256 "a7e762346ddcffd573f77db743f2b33d567ca4e60d1f09879f3c9b16d98b2092"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Linux_x86_64.tar.gz"
      sha256 "e62704eb211ccd4cfba9ef3a5e8c8f6ca86782064e1f33c592a863f329b1a0da"
    end
    on_arm do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Linux_arm64.tar.gz"
      sha256 "49c3e075c1d4b821ee5436ffb277375230d36e145e7f1d7cdb4a8ce17b019b41"
    end
  end

  caveats do
    "recovercheck is a tool to check for panic recovery in Go code."
    "Run 'recovercheck' to start the tool."
  end

  # No zap stanza required
end
