# This file was generated by GoReleaser. DO NOT EDIT.
cask "recovercheck" do
  name "recovercheck"
  desc "A tool to check for panic recovery in Go code"
  homepage "https://github.com/cksidharthan/recovercheck"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recovercheck"

  on_macos do
    on_intel do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Darwin_x86_64.tar.gz"
      sha256 "48125de6cba4271b33fae83c53a2cca10231721fdd188b92fc5d0b2cf0a1bc7c"
    end
    on_arm do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Darwin_arm64.tar.gz"
      sha256 "6720bbcf72aad1dfcb7135daca3867b83662a062b79ced10da615110602c2c05"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Linux_x86_64.tar.gz"
      sha256 "d78c7c37305aab63c328eaa9cca4e46fb2b46356bf28c805fc334ac214d9b576"
    end
    on_arm do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v#{version}/recovercheck_Linux_arm64.tar.gz"
      sha256 "e699bc73e3ae6a788202e763644f70a69878b6cd277f314343fe03c56a704c5e"
    end
  end

  caveats do
    "recovercheck is a tool to check for panic recovery in Go code."
    "Run 'recovercheck' to start the tool."
  end

  # No zap stanza required
end
