# This file was generated by GoReleaser. DO NOT EDIT.
cask "recovercheck" do
  desc "A tool to check for panic recovery in Go code"
  homepage "https://github.com/cksidharthan/recovercheck"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recovercheck"

  on_macos do
    on_intel do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.4.0/recovercheck_Darwin_x86_64.tar.gz"
      sha256 "7dbf4ba2851eeb9fc8772d647889a2afa256eef975925d1b02387fb1d4882d6c"
    end
    on_arm do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.4.0/recovercheck_Darwin_arm64.tar.gz"
      sha256 "74d61ff7ddb0090066b5846d6c8cfa8454bede232ceef4bf6ad866f5039acf55"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.4.0/recovercheck_Linux_x86_64.tar.gz"
      sha256 "e00e763f46f40bb83ad5b2ea7f3f3afb64723b5a9f837626d841cd65b1b27d28"
    end
    on_arm do
      url "https://github.com/cksidharthan/recovercheck/releases/download/v1.4.0/recovercheck_Linux_arm64.tar.gz"
      sha256 "23ad5c54c687adf7e325dee75c5d2f76fb203408cb61afc2afa1dd2c553fada4"
    end
  end

  caveats do
    "recovercheck is a tool to check for panic recovery in Go code."
    "Run 'recovercheck' to start the tool."
  end

  # No zap stanza required
end
